version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'goBotDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'botUser'
      # You can use whatever password you like
      MYSQL_PASSWORD: ${BOTDB_USER_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${BOTDB_ROOT_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./initialScript/initial-script.sql:/docker-entrypoint-initdb.d/initial-script.sql
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: